# Generated by Django 4.2.6 on 2023-10-16 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='start_sending_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 16, 16, 36, 14, 565955), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_sending_time',
            field=models.TimeField(blank=True, default=datetime.time(16, 36, 14, 565964), null=True, verbose_name='время рассылки'),
        ),
    ]
